project:
  name: "transaction-event-bridge"
  version: "1.0.0-SNAPSHOT"
  description: "IBM MQ and Apache Kafka for real-time event bridge"

spring:
  application:
    name: ${project.name}
  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always